source 'http://rubygems.org'

gem 'rails', '3.1.0'

gem 'brazilian-rails'	# impĺementa layout brasileiro
gem 'devise'			# faz autenticação
gem 'jquery-rails'		# implementa JQuery
gem 'kaminari'			# faz a paginação de dados

gem 'thin'				# servidor padrao de Ruby on Rails

# gem 'pg', group: :production

group :development	do
	gem 'sqlite3'
end

group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

group :development, :test do
	gem 'therubyracer'
	gem 'rspec-rails' 
end
