source 'http://rubygems.org'

gem 'rails', '3.1.0'
gem 'sqlite3', :group => :development
gem 'pg', :group => :production

group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'heroku', :group => :development
gem 'jquery-rails'
gem 'execjs'
gem 'therubyracer'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
